### PR TITLE
Add suport to select by RegExp and negative selection.

### PR DESCRIPTION
**Pull request by aurium**
Find one whose name starts with "R": `jsonQuery("people[name~/^R/i]", {data: data});`

Find one whose is not green: `jsonQuery("objects[color!=green]", {data: data});`

### CODE REVIEW

**Comment by aurium** [comment]
I did not roll up the version (`1.5.0`). I believe it is a "minor", but you (not me) should decide where to change the module version. :-)

**Comment by mmckegg** [comment]
Thanks for taking the time to do this! Though, I think this would be a lot more useful if `json-query` supported returning multiple results.

What was your use case for adding this support?

**Comment by aurium** [comment]
Thank you @mmckegg! I really agree with you! However multiple return may crash the current users... I think that must be enabled by an extra option like `multiple:true`.

This feature is important *(to me and friends at least)* because we want to make our simple winston-log-file query better and i like the json-query notation. But we wont to use filters for regexp or we will still work on our garbage.

**Comment by aurium** [comment]
Hi... Is this ok?

**Comment by mmckegg** [comment]
@aurium: I'd be happy to merge if the regexp matching was put behind an option like `allowRegexp: true`.

There are [a few security issues](http://stackoverflow.com/questions/20928677/user-defined-regular-expression-security-concerns) with regular expressions, and I use this module as a user facing query language.

**Comment by aurium** [comment]
Hummm... interesting. Ok, i will add the `allowRegexp` option.

**Comment by mmckegg** [comment]
:+1:

**Comment by mmckegg** [comment]
published as v1.6.0 :tada:

**Comment by aurium** [comment]
:smiley: :tada:

**Pull request merged**
